In [5]:
import yfinance as yf
import pandas as pd
import numpy as np

In [14]:
cola = yf.Ticker('KO')
cola_balance = cola.balance_sheet
cola_income = cola.income_stmt
cola_cf = cola.cash_flow

In [13]:
pepsi = yf.Ticker('PEP')
pepsi_balance = pepsi.balance_sheet
pepsi_income = pepsi.income_stmt
pepsi_cf = pepsi.cash_flow

In [46]:
pepsi_income.head(100)

,2022-12-31,2021-12-31,2020-12-31,2019-12-31
Tax Effect Of Unusual Items,31000000.0,0.0,0.0,0.0
Tax Rate For Calcs,0.2,0.218,0.209,0.21
Normalized EBITDA,14769000000.0,14899000000.0,12745000000.0,12879000000.0
Total Unusual Items,155000000.0,NaN,NaN,NaN
Total Unusual Items Excluding Goodwill,155000000.0,NaN,NaN,NaN
Net Income From Continuing Operation Net Minority Interest,8910000000.0,7618000000.0,7120000000.0,7314000000.0
Reconciled Depreciation,3280000000.0,3215000000.0,2548000000.0,2432000000.0
Reconciled Cost Of Revenue,40576000000.0,37075000000.0,31797000000.0,30132000000.0
EBITDA,14924000000.0,14899000000.0,12745000000.0,12879000000.0
EBIT,11644000000.0,11684000000.0,10197000000.0,10447000000.0
Net Interest Income,-939000000.0,-1863000000.0,-1128000000.0,-935000000.0
Interest Expense,939000000.0,1863000000.0,1128000000.0,1135000000.0
Interest Income,NaN,NaN,NaN,200000000.0
Normalized Income,8786000000.0,7618000000.0,7120000000.0,7314000000.0
Net Income From Continuing And Discontinued Operation,8910000000.0,7618000000.0,7120000000.0,7314000000.0
Total Expenses,75035000000.0,68312000000.0,60292000000.0,56870000000.0
Total Operating Income As Reported,11512000000.0,11162000000.0,10080000000.0,10291000000.0
Diluted Average Shares,1387000000.0,1389000000.0,1392000000.0,1407000000.0
Basic Average Shares,1380000000.0,1383000000.0,1380000000.0,1391000000.0
Diluted EPS,6.42,5.49,5.12,5.2
Basic EPS,6.45,5.508315,5.15942,5.258088
Diluted NI Availto Com Stockholders,8910000000.0,7618000000.0,7120000000.0,7314000000.0
Average Dilution Earnings,NaN,NaN,0.0,0.0
Net Income Common Stockholders,8910000000.0,7618000000.0,7120000000.0,7314000000.0
Otherunder Preferred Stock Dividend,NaN,NaN,0.0,0.0
Net Income,8910000000.0,7618000000.0,7120000000.0,7314000000.0
Minority Interests,-68000000.0,-61000000.0,-55000000.0,-39000000.0
Net Income Including Noncontrolling Interests,8978000000.0,7679000000.0,7175000000.0,7353000000.0
Net Income Continuous Operations,8978000000.0,7679000000.0,7175000000.0,7353000000.0
Tax Provision,1727000000.0,2142000000.0,1894000000.0,1959000000.0
Pretax Income,10705000000.0,9821000000.0,9069000000.0,9312000000.0
Other Income Expense,287000000.0,522000000.0,117000000.0,-44000000.0
Other Non Operating Income Expenses,132000000.0,522000000.0,117000000.0,-44000000.0
Special Income Charges,155000000.0,NaN,NaN,NaN
Impairment Of Capital Assets,3166000000.0,NaN,NaN,NaN
Restructuring And Mergern Acquisition,-3321000000.0,NaN,NaN,NaN
Net Non Operating Interest Income Expense,-939000000.0,-1863000000.0,-1128000000.0,-935000000.0
Interest Expense Non Operating,939000000.0,1863000000.0,1128000000.0,1135000000.0
Interest Income Non Operating,NaN,NaN,NaN,200000000.0
Operating Income,11357000000.0,11162000000.0,10080000000.0,10291000000.0
Operating Expense,34459000000.0,31237000000.0,28495000000.0,26738000000.0
Selling General And Administration,34459000000.0,31237000000.0,28495000000.0,26738000000.0
Gross Profit,45816000000.0,42399000000.0,38575000000.0,37029000000.0
Cost Of Revenue,40576000000.0,37075000000.0,31797000000.0,30132000000.0
Total Revenue,86392000000.0,79474000000.0,70372000000.0,67161000000.0
Operating Revenue,86392000000.0,79474000000.0,70372000000.0,67161000000.0

In [38]:
#get for quarterly report
cola_balance_quarter=yf.Ticker('KO').quarterly_balance_sheet
cola_income_quarter=yf.Ticker('KO').quarterly_income_stmt
cola_cf_quarter=yf.Ticker('KO').quarterly_cashflow

pepsi_balance_quarter=yf.Ticker('PEP').quarterly_balance_sheet
pepsi_income_quarter=yf.Ticker('PEP').quarterly_income_stmt
pepsi_cf_quarter=yf.Ticker('PEP').quarterly_cashflow

In [40]:
cola_balance_quarter.head()
pepsi_balance_quarter.head()

,2023-09-30,2023-06-30,2023-03-31,2022-12-31,2022-09-30
Treasury Shares Number,492000000.0,490000000.0,489000000.0,490000000.0,NaN
Ordinary Shares Number,1374863961.0,1376580611.0,1378000000.0,1377000000.0,1377709209.0
Share Issued,1866863961.0,1866580611.0,1867000000.0,1867000000.0,1377709209.0
Net Debt,34757000000.0,37505000000.0,36997000000.0,34117000000.0,32830000000.0
Total Debt,44774000000.0,43621000000.0,41767000000.0,39071000000.0,39245000000.0

#The observation around financial metrics will be concentrated on
### business volume 
#### -total revenue
#### -revenue growth
#### -revenue structure/ per geo or per business
#### -non-financial market stats
### profitability
#### -gross margin/ebit
#### -marketing investment
#### -cost/expense analysis
### solvency and liquidity
#### -leverage ratio
#### -ebit/interest ratio
#### -liquidity ratios
### working capital efficiency
#### -DSO
#### -ITO
#### -DPO
#### -CCC
### capital market performance
#### -MARKET CAP and price
#### -EPS/PE ratio/PB ratio

In [42]:
# total sales
cola_income_quarter.head(200)

,2023-09-30,2023-06-30,2023-03-31,2022-12-31,2022-09-30
Tax Effect Of Unusual Items,0.0,0.0,0.0,0.0,0.0
Tax Rate For Calcs,0.128,0.125,0.232,0.177,0.181
Normalized EBITDA,4195000000.0,3535000000.0,4711000000.0,3111000000.0,3949000000.0
Total Unusual Items,-428000000.0,-1314000000.0,NaN,-88000000.0,-104000000.0
Total Unusual Items Excluding Goodwill,-428000000.0,-1314000000.0,NaN,-88000000.0,-104000000.0
Net Income From Continuing Operation Net Minority Interest,3087000000.0,2547000000.0,3107000000.0,2031000000.0,2825000000.0
Reconciled Depreciation,290000000.0,281000000.0,286000000.0,307000000.0,307000000.0
Reconciled Cost Of Revenue,4657000000.0,4912000000.0,4317000000.0,4513000000.0,4566000000.0
EBITDA,4195000000.0,3535000000.0,4711000000.0,3111000000.0,3949000000.0
EBIT,3905000000.0,3254000000.0,4425000000.0,2804000000.0,3642000000.0
Net Interest Income,-120000000.0,-150000000.0,-204000000.0,-161000000.0,-70000000.0
Interest Expense,368000000.0,374000000.0,372000000.0,304000000.0,198000000.0
Interest Income,248000000.0,224000000.0,168000000.0,143000000.0,128000000.0
Normalized Income,3087000000.0,2547000000.0,3107000000.0,2031000000.0,2825000000.0
Net Income From Continuing And Discontinued Operation,3087000000.0,2547000000.0,3107000000.0,2031000000.0,2825000000.0
Total Expenses,8683000000.0,9571000000.0,7613000000.0,8050000000.0,7975000000.0
Total Operating Income As Reported,3270000000.0,2401000000.0,3367000000.0,2075000000.0,3088000000.0
Diluted Average Shares,4339000000.0,4341000000.0,4345000000.0,4347000000.0,4346000000.0
Basic Average Shares,4324000000.0,4325000000.0,4326000000.0,4326000000.0,4325000000.0
Diluted EPS,0.71,0.59,0.72,0.47,0.65
Basic EPS,0.71,0.59,0.72,0.47,0.65
Diluted NI Availto Com Stockholders,3087000000.0,2547000000.0,3107000000.0,2031000000.0,2825000000.0
Net Income Common Stockholders,3087000000.0,2547000000.0,3107000000.0,2031000000.0,2825000000.0
Net Income,3087000000.0,2547000000.0,3107000000.0,2031000000.0,2825000000.0
Minority Interests,4000000.0,26000000.0,-6000000.0,-25000000.0,3000000.0
Net Income Including Noncontrolling Interests,3083000000.0,2521000000.0,3113000000.0,2056000000.0,2822000000.0
Net Income Continuous Operations,3083000000.0,2521000000.0,3113000000.0,2056000000.0,2822000000.0
Tax Provision,454000000.0,359000000.0,940000000.0,444000000.0,622000000.0
Pretax Income,3537000000.0,2880000000.0,4053000000.0,2500000000.0,3444000000.0
Other Income Expense,387000000.0,629000000.0,890000000.0,586000000.0,426000000.0
Other Non Operating Income Expenses,-130000000.0,91000000.0,615000000.0,247000000.0,-53000000.0
Special Income Charges,-301000000.0,-1314000000.0,NaN,-88000000.0,-104000000.0
Gain On Sale Of Business,NaN,-35000000.0,NaN,NaN,NaN
Other Special Charges,1000000.0,6000000.0,NaN,NaN,NaN
Impairment Of Capital Assets,NaN,NaN,NaN,0.0,57000000.0
Restructuring And Mergern Acquisition,300000000.0,1273000000.0,NaN,88000000.0,47000000.0
Earnings From Equity Interest,517000000.0,538000000.0,275000000.0,339000000.0,479000000.0
Gain On Sale Of Security,-127000000.0,93000000.0,NaN,NaN,NaN
Net Non Operating Interest Income Expense,-120000000.0,-150000000.0,-204000000.0,-161000000.0,-70000000.0
Interest Expense Non Operating,368000000.0,374000000.0,372000000.0,304000000.0,198000000.0
Interest Income Non Operating,248000000.0,224000000.0,168000000.0,143000000.0,128000000.0
Operating Income,3270000000.0,2401000000.0,3367000000.0,2075000000.0,3088000000.0
Operating Expense,4026000000.0,4659000000.0,3296000000.0,3537000000.0,3409000000.0
Other Operating Expenses,359000000.0,1338000000.0,111000000.0,106000000.0,130000000.0
Selling General And Administration,3667000000.0,3321000000.0,3185000000.0,3431000000.0,3279000000.0
Selling And Marketing Expense,2220000000.0,1901000000.0,1719000000.0,1584000000.0,2014000000.0
General And Administrative Expense,57000000.0,62000000.0,58000000.0,83000000.0,84000000.0
Other Gand A,NaN,NaN,NaN,NaN,1181000000.0
Salaries And Wages,57000000.0,62000000.0,58000000.0,83000000.0,84000000.0
Gross Profit,7296000000.0,7060000000.0,6663000000.0,5612000000.0,6497000000.0
Cost Of Revenue,4657000000.0,4912000000.0,4317000000.0,4513000000.0,4566000000.0
Total Revenue,11953000000.0,11972000000.0,10980000000.0,10125000000.0,11063000000.0
Operating Revenue,11953000000.0,11972000000.0,10980000000.0,10125000000.0,11063000000.0

In [43]:
pepsi_income_quarter.head(200)

,2023-09-30,2023-06-30,2023-03-31,2022-12-31,2022-09-30
Tax Effect Of Unusual Items,-1170000.0,0.0,0.0,-254932000.0,-2235000.0
Tax Rate For Calcs,0.195,0.213,0.219,0.163,0.149
Normalized EBITDA,4083000000.0,4529000000.0,3396000000.0,2343000000.0,4186000000.0
Total Unusual Items,-6000000.0,0.0,0.0,-1564000000.0,-15000000.0
Total Unusual Items Excluding Goodwill,-6000000.0,0.0,0.0,-1564000000.0,-15000000.0
Net Income From Continuing Operation Net Minority Interest,3092000000.0,2748000000.0,1932000000.0,518000000.0,2702000000.0
Reconciled Depreciation,841000000.0,810000000.0,706000000.0,1080000000.0,782000000.0
Reconciled Cost Of Revenue,10675000000.0,10121000000.0,7988000000.0,13420000000.0,10308000000.0
EBITDA,4077000000.0,4529000000.0,3396000000.0,779000000.0,4171000000.0
EBIT,4077000000.0,3719000000.0,2690000000.0,779000000.0,3389000000.0
Net Interest Income,-201000000.0,-201000000.0,-200000000.0,-273000000.0,-190000000.0
Interest Expense,201000000.0,201000000.0,200000000.0,273000000.0,190000000.0
Normalized Income,3096830000.0,2748000000.0,1932000000.0,1827068000.0,2714765000.0
Net Income From Continuing And Discontinued Operation,3092000000.0,2748000000.0,1932000000.0,518000000.0,2702000000.0
Total Expenses,19432000000.0,18663000000.0,15217000000.0,25617000000.0,18603000000.0
Total Operating Income As Reported,4015000000.0,3659000000.0,2629000000.0,815000000.0,3353000000.0
Diluted Average Shares,1383000000.0,1384000000.0,1384000000.0,1385000000.0,1387000000.0
Basic Average Shares,1376000000.0,1378000000.0,1378000000.0,1377000000.0,1380000000.0
Diluted EPS,2.24,1.99,1.4,0.37,1.95
Basic EPS,2.25,1.99,1.4,0.37618,1.96
Diluted NI Availto Com Stockholders,3092000000.0,2748000000.0,1932000000.0,518000000.0,2702000000.0
Average Dilution Earnings,0.0,0.0,0.0,NaN,0.0
Net Income Common Stockholders,3092000000.0,2748000000.0,1932000000.0,518000000.0,2702000000.0
Net Income,3092000000.0,2748000000.0,1932000000.0,518000000.0,2702000000.0
Minority Interests,-24000000.0,-23000000.0,-12000000.0,-17000000.0,-22000000.0
Net Income Including Noncontrolling Interests,3116000000.0,2771000000.0,1944000000.0,535000000.0,2724000000.0
Net Income Continuous Operations,3116000000.0,2771000000.0,1944000000.0,535000000.0,2724000000.0
Tax Provision,760000000.0,747000000.0,546000000.0,-29000000.0,475000000.0
Pretax Income,3876000000.0,3518000000.0,2490000000.0,506000000.0,3199000000.0
Other Income Expense,56000000.0,60000000.0,61000000.0,-1600000000.0,21000000.0
Other Non Operating Income Expenses,62000000.0,60000000.0,61000000.0,-36000000.0,36000000.0
Special Income Charges,-6000000.0,0.0,0.0,-1564000000.0,-15000000.0
Impairment Of Capital Assets,6000000.0,0.0,0.0,1564000000.0,1000000.0
Restructuring And Mergern Acquisition,0.0,0.0,0.0,0.0,14000000.0
Net Non Operating Interest Income Expense,-201000000.0,-201000000.0,-200000000.0,-273000000.0,-190000000.0
Interest Expense Non Operating,201000000.0,201000000.0,200000000.0,273000000.0,190000000.0
Operating Income,4021000000.0,3659000000.0,2629000000.0,2379000000.0,3368000000.0
Operating Expense,8757000000.0,8542000000.0,7229000000.0,12197000000.0,8295000000.0
Selling General And Administration,8757000000.0,8542000000.0,7229000000.0,12197000000.0,8295000000.0
Gross Profit,12778000000.0,12201000000.0,9858000000.0,14576000000.0,11663000000.0
Cost Of Revenue,10675000000.0,10121000000.0,7988000000.0,13420000000.0,10308000000.0
Total Revenue,23453000000.0,22322000000.0,17846000000.0,27996000000.0,21971000000.0
Operating Revenue,23453000000.0,22322000000.0,17846000000.0,27996000000.0,21971000000.0

In [47]:
#1.transform 12 tables
#1.1 add company labels
# coke 10k
cola_balance.insert(0, 'Company Name', 'coca')
cola_income.insert(0, 'Company Name', 'coca')
cola_cf.insert(0, 'Company Name', 'coca')

# pepsi 10k
pepsi_balance.insert(0, 'Company Name', 'pepsi')
pepsi_income.insert(0, 'Company Name', 'pepsi')
pepsi_cf.insert(0, 'Company Name', 'pepsi')

In [49]:
pepsi_balance

,Company Name,2022-12-31 00:00:00,2021-12-31 00:00:00,2020-12-31 00:00:00,2019-12-31 00:00:00
Treasury Shares Number,pepsi,490000000.0,484000000.0,487000000.0,476000000.0
Ordinary Shares Number,pepsi,1377000000.0,1383000000.0,1380000000.0,1391000000.0
Share Issued,pepsi,1867000000.0,1867000000.0,1867000000.0,1867000000.0
Net Debt,pepsi,34117000000.0,34738000000.0,35965000000.0,26559000000.0
Total Debt,pepsi,39071000000.0,40334000000.0,44150000000.0,32068000000.0
...,...,...,...,...,...
Other Receivables,pepsi,2121000000.0,1655000000.0,1713000000.0,1480000000.0
Accounts Receivable,pepsi,10163000000.0,8680000000.0,8404000000.0,7822000000.0
Cash Cash Equivalents And Short Term Investments,pepsi,5348000000.0,5988000000.0,9551000000.0,5738000000.0
Other Short Term Investments,pepsi,394000000.0,392000000.0,1366000000.0,229000000.0
Cash And Cash Equivalents,pepsi,4954000000.0,5596000000.0,8185000000.0,5509000000.0

In [50]:
pepsi_balance.columns = [col.strftime('%Y-%m-%d') if isinstance(col, pd.Timestamp) else col for col in pepsi_balance.columns]
pepsi_income.columns = [col.strftime('%Y-%m-%d') if isinstance(col, pd.Timestamp) else col for col in pepsi_income.columns]
pepsi_cf.columns = [col.strftime('%Y-%m-%d') if isinstance(col, pd.Timestamp) else col for col in pepsi_cf.columns]

In [53]:
cola_balance.columns = [col.strftime('%Y-%m-%d') if isinstance(col, pd.Timestamp) else col for col in cola_balance.columns]
cola_income.columns = [col.strftime('%Y-%m-%d') if isinstance(col, pd.Timestamp) else col for col in cola_income.columns]
cola_cf.columns = [col.strftime('%Y-%m-%d') if isinstance(col, pd.Timestamp) else col for col in cola_cf.columns]

In [55]:
#labelize data source
#cola 10k
cola_balance.insert(0, 'Data Source', 'bs')
cola_income.insert(0, 'Data Source', 'is')
cola_cf.insert(0, 'Data Source', 'cf')

# pepsi 10k
pepsi_balance.insert(0, 'Data Source', 'bs')
pepsi_income.insert(0, 'Data Source', 'is')
pepsi_cf.insert(0, 'Data Source', 'cf')

In [57]:
# index to indicators
# cola
cola_balance = cola_balance.reset_index().rename(columns={'index': 'Financial Indicators'})
cola_income = cola_income.reset_index().rename(columns={'index': 'Financial Indicators'})
cola_cf = cola_cf.reset_index().rename(columns={'index': 'Financial Indicators'})

# pepsi
pepsi_balance = pepsi_balance.reset_index().rename(columns={'index': 'Financial Indicators'})
pepsi_income = pepsi_income.reset_index().rename(columns={'index': 'Financial Indicators'})
pepsi_cf = pepsi_cf.reset_index().rename(columns={'index': 'Financial Indicators'})

In [63]:
pepsi_balance

,Financial Indicators,Data Source,Company Name,2022-12-31,2021-12-31,2020-12-31,2019-12-31
0,Treasury Shares Number,bs,pepsi,490000000.0,484000000.0,487000000.0,476000000.0
1,Ordinary Shares Number,bs,pepsi,1377000000.0,1383000000.0,1380000000.0,1391000000.0
2,Share Issued,bs,pepsi,1867000000.0,1867000000.0,1867000000.0,1867000000.0
3,Net Debt,bs,pepsi,34117000000.0,34738000000.0,35965000000.0,26559000000.0
4,Total Debt,bs,pepsi,39071000000.0,40334000000.0,44150000000.0,32068000000.0
...,...,...,...,...,...,...,...
77,Other Receivables,bs,pepsi,2121000000.0,1655000000.0,1713000000.0,1480000000.0
78,Accounts Receivable,bs,pepsi,10163000000.0,8680000000.0,8404000000.0,7822000000.0
79,Cash Cash Equivalents And Short Term Investments,bs,pepsi,5348000000.0,5988000000.0,9551000000.0,5738000000.0
80,Other Short Term Investments,bs,pepsi,394000000.0,392000000.0,1366000000.0,229000000.0
81,Cash And Cash Equivalents,bs,pepsi,4954000000.0,5596000000.0,8185000000.0,5509000000.0

In [64]:
form10k_inone=pd.concat([cola_balance,cola_income,cola_cf,pepsi_balance,pepsi_income,pepsi_cf])

In [65]:
form10k_inone

,Financial Indicators,Data Source,Company Name,2022-12-31,2021-12-31,2020-12-31,2019-12-31
0,Treasury Shares Number,bs,coca,2712000000.0,2715000000.0,2738000000.0,2760000000.0
1,Ordinary Shares Number,bs,coca,4328000000.0,4325128924.0,4302128924.0,4280128924.0
2,Share Issued,bs,coca,7040000000.0,7040128924.0,7040128924.0,7040128924.0
3,Net Debt,bs,coca,29630000000.0,33077000000.0,35998000000.0,36283000000.0
4,Total Debt,bs,coca,39149000000.0,42761000000.0,42793000000.0,42763000000.0
...,...,...,...,...,...,...,...
59,Depreciation,cf,pepsi,3280000000.0,3215000000.0,NaN,NaN
60,Operating Gains Losses,cf,pepsi,-2902000000.0,123000000.0,408000000.0,519000000.0
61,Pension And Employee Benefit Expense,cf,pepsi,419000000.0,123000000.0,408000000.0,519000000.0
62,Gain Loss On Sale Of Business,cf,pepsi,-3321000000.0,NaN,NaN,NaN
63,Net Income From Continuing Operations,cf,pepsi,8978000000.0,7679000000.0,7175000000.0,7353000000.0

In [66]:
form10k_inone.to_excel('form10k_inone.xlsx')